// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwTK29y0PkKu-pCbIf6RoozygFlNAp6WY',
    appId: '1:765155375047:web:8bc39835d7147233c6cbe2',
    messagingSenderId: '765155375047',
    projectId: 'yours-cook-book',
    authDomain: 'yours-cook-book.firebaseapp.com',
    storageBucket: 'yours-cook-book.firebasestorage.app',
    measurementId: 'G-YBNT5XTWQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUeARS3kIDcIhc8r2o2TQBwqjE3f__1o',
    appId: '1:765155375047:android:11fce71ccb99507cc6cbe2',
    messagingSenderId: '765155375047',
    projectId: 'yours-cook-book',
    storageBucket: 'yours-cook-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTtCBARG4JNbWzasJs7uAY-v-z-Mb8etU',
    appId: '1:765155375047:ios:02985dfcb79f2cdcc6cbe2',
    messagingSenderId: '765155375047',
    projectId: 'yours-cook-book',
    storageBucket: 'yours-cook-book.firebasestorage.app',
    iosBundleId: 'com.example.cookBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTtCBARG4JNbWzasJs7uAY-v-z-Mb8etU',
    appId: '1:765155375047:ios:02985dfcb79f2cdcc6cbe2',
    messagingSenderId: '765155375047',
    projectId: 'yours-cook-book',
    storageBucket: 'yours-cook-book.firebasestorage.app',
    iosBundleId: 'com.example.cookBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwTK29y0PkKu-pCbIf6RoozygFlNAp6WY',
    appId: '1:765155375047:web:ddacc8e8a5feda03c6cbe2',
    messagingSenderId: '765155375047',
    projectId: 'yours-cook-book',
    authDomain: 'yours-cook-book.firebaseapp.com',
    storageBucket: 'yours-cook-book.firebasestorage.app',
    measurementId: 'G-XQPM791500',
  );
}
